# Generated by Django 4.1 on 2023-04-09 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Model", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="room", table="room_info",),
    ]
