# Generated by Django 4.1 on 2023-04-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Model", "0002_alter_room_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seat",
            name="can_charge",
            field=models.BooleanField(default=False, verbose_name="是否可充电"),
        ),
    ]
