# Generated by Django 4.1 on 2023-04-09 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Model", "0004_alter_user_managers_rename_is_admin_user_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="building",
            options={"verbose_name": "教学楼管理", "verbose_name_plural": "教学楼管理"},
        ),
        migrations.AlterModelOptions(
            name="campus",
            options={"verbose_name": "校区管理", "verbose_name_plural": "校区管理"},
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={"verbose_name": "预约记录管理", "verbose_name_plural": "预约记录管理"},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"verbose_name": "自习室管理", "verbose_name_plural": "自习室管理"},
        ),
        migrations.AlterModelOptions(
            name="seat",
            options={"verbose_name": "座位管理", "verbose_name_plural": "座位管理"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "用户管理", "verbose_name_plural": "用户管理"},
        ),
    ]
