# Generated by Django 4.1 on 2023-04-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Model", "0005_alter_building_options_alter_campus_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="number_of_seats",
            field=models.PositiveIntegerField(default=50, verbose_name="座位数量"),
        ),
    ]
