# Generated by Django 4.1 on 2023-04-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Model", "0007_alter_room_room_id_alter_seat_seat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="have_charge",
            field=models.BooleanField(default=False, verbose_name="是否有充电设备"),
        ),
        migrations.AlterField(
            model_name="room",
            name="number_of_seats",
            field=models.PositiveIntegerField(default=0, verbose_name="座位数量"),
        ),
    ]
