# Generated by Django 4.1 on 2023-04-16 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Model", "0008_alter_room_have_charge_alter_room_number_of_seats"),
    ]

    operations = [
        migrations.AlterModelManagers(name="user", managers=[],),
    ]
