# Generated by Django 4.1 on 2023-04-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Model", "0009_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seat",
            name="QR_Code",
            field=models.URLField(blank=True, null=True, verbose_name="二维码链接"),
        ),
    ]
